class PyPhiResponse:
    code: int
    mime: str
    data: bytes

def init(files: list[str], image_format: str, cldb_data: bytes) -> None: ...
def reset() -> None: ...
def call_router(path: str) -> PyPhiResponse: ...
def get_image_formats() -> list[str]: ...